//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversCorps.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocHei
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LocHei()
        {
            this.UniClassFundCorps = new HashSet<UniClassFundCorps>();
        }
    
        public int Id { get; set; }
        public int IdLocation { get; set; }
        public int IdCeiling { get; set; }
    
        public virtual Ceiling Ceiling { get; set; }
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UniClassFundCorps> UniClassFundCorps { get; set; }
    }
}
