//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversCorps.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniClassFundCorps
    {
        public int Id { get; set; }
        public int IdCorps { get; set; }
        public int Room { get; set; }
        public Nullable<int> IdLocHei { get; set; }
        public Nullable<double> WidthMeters { get; set; }
        public Nullable<double> LengthMeters { get; set; }
        public Nullable<int> IdPurporse { get; set; }
        public Nullable<int> IdTypeOfRoom { get; set; }
        public int IdDivision { get; set; }
    
        public virtual Corps Corps { get; set; }
        public virtual Division Division { get; set; }
        public virtual LocHei LocHei { get; set; }
        public virtual Purporse Purporse { get; set; }
        public virtual TypeOfRoom TypeOfRoom { get; set; }
    }
}
